// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
  site: 'https://osctrl.net',
  integrations: [
    starlight({
      title: 'osctrl',
      description: 'Documentation for osctrl: Fast and efficient osquery management',
      logo: {
        src: './src/assets/osctrl-logo-dark.png',
        alt: 'osctrl',
        replacesTitle: false,
      },
      favicon: '/favicon.svg',
      customCss: ['./src/styles/osctrl.css'],
      // Inter / Space Grotesk / IBM Plex Mono, the same three families the
      // frontend uses. Bai Jamjuree is self-hosted from public/fonts/.
      head: [
        {
          tag: 'link',
          attrs: { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
        },
        {
          tag: 'link',
          attrs: {
            rel: 'preconnect',
            href: 'https://fonts.gstatic.com',
            crossorigin: true,
          },
        },
        {
          tag: 'link',
          attrs: {
            rel: 'stylesheet',
            href: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&family=IBM+Plex+Mono:wght@400;600&display=swap',
          },
        },
      ],
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/jmpsec/osctrl',
        }
      ],
      editLink: {
        baseUrl: 'https://github.com/jmpsec/osctrl-docs/edit/master/docs-next/',
      },
      // Written out explicitly rather than autogenerated. The Hugo weights
      // had collisions (osctrl-tls and osctrld both weight 1; osctrl-admin
      // and osctrl-api both weight 2), and an autogenerated section index
      // sorts among its own children. Section order still follows the Hugo
      // numbering: components 1, deployment 2, configuration 3, usage 4,
      // contributing 5.
      sidebar: [
        {
          label: '1. Components',
          items: [
            { slug: 'components', label: 'Overview' },
            'components/osctrl-tls',
            'components/osctrl-admin',
            'components/osctrl-api',
            'components/osctrl-cli',
            'components/nginx',
            'components/backend',
            'components/metrics',
            'components/osctrld',
          ],
        },
        {
          label: '2. Deployment',
          items: [
            { slug: 'deployment', label: 'Overview' },
            'deployment/docker',
            'deployment/natively',
          ],
        },
        {
          label: '3. Configuration',
          items: ['configuration'],
        },
        {
          label: '4. Usage',
          items: [
            { slug: 'usage', label: 'Overview' },
            'usage/osctrl-tls',
            'usage/osctrl-admin',
            'usage/osctrl-api',
            {
              label: 'osctrl-cli',
              collapsed: true,
              items: [
                { slug: 'usage/osctrl-cli', label: 'Overview' },
                'usage/osctrl-cli/audit-logs',
                'usage/osctrl-cli/carve',
                'usage/osctrl-cli/check-api',
                'usage/osctrl-cli/check-db',
                'usage/osctrl-cli/environment',
                'usage/osctrl-cli/login',
                'usage/osctrl-cli/node',
                'usage/osctrl-cli/query',
                'usage/osctrl-cli/settings',
                'usage/osctrl-cli/shell',
                'usage/osctrl-cli/tag',
                'usage/osctrl-cli/user',
              ],
            },
            'usage/osctrld',
            'usage/provision.sh',
          ],
        },
        {
          label: '5. Contributing',
          items: ['contributing'],
        },
        {
          label: 'API reference',
          items: [
            {
              label: 'osctrl-api (OpenAPI)',
              link: '/openapi/doc.html',
              attrs: { target: '_blank' },
            },
          ],
        },
      ],
      lastUpdated: true,
    }),
  ],
});
